define([], function () {
  return {
    PropertyPaneDescription: 'AI Upload converts a scanned PDF to text using on-device OCR.',
    BasicGroupName: 'Settings',
    DescriptionFieldLabel: 'Description',
    WebPartTitle: 'AI Upload',
    WebPartSubtitle: 'Upload a scanned PDF and run OCR. Fields are filled by AI from the document meaning, even when labels differ.',
    SelectPdfLabel: 'PDF file',
    ChooseFile: 'Choose PDF',
    OcrLanguageLabel: 'OCR language',
    ConvertButton: 'Convert to OCR',
    ExtractedTextLabel: 'Extracted text',
    ExtractedTextPlaceholder: 'OCR results will appear here after conversion.',
    PdfPreviewLabel: 'PDF preview',
    PdfPreviewPlaceholder: 'The OCR PDF preview will appear here after conversion.',
    PreviousPage: 'Previous page',
    NextPage: 'Next page',
    FormFieldsLabel: 'Form fields',
    FormFieldsFieldLabel: 'Field names (one per line)',
    FormFieldsFieldDescription: 'These text boxes are filled after OCR. Click a field and highlight the PDF to correct a value.',
    AiGroupName: 'AI extraction',
    AzureEndpointLabel: 'Azure OpenAI endpoint',
    AzureEndpointDescription: 'Example: https://YOUR-RESOURCE.openai.azure.com  (or https://api.openai.com)',
    AzureDeploymentLabel: 'Deployment name',
    AzureDeploymentDescription: 'Azure OpenAI deployment name, for example gpt-4o-mini. Use a vision model so letterhead logos can be read. Not required for api.openai.com.',
    AzureApiKeyLabel: 'API key',
    AzureApiKeyDescription: 'Stored in this web part. Page editors can see it. Required to auto-fill fields when documents have no matching labels.',
    AzureApiVersionLabel: 'API version',
    ExtractingFields: 'Reading the document and letterhead, then filling fields…',
    AiExtractFailed: 'AI field extraction failed. Label matching was used instead.',
    AiNotConfiguredHint: 'Azure OpenAI is not configured, so fields are filled only when matching labels appear in the PDF. Edit this web part and add an endpoint, deployment, and API key to fill fields by meaning.',
    AiCorsFailed: 'The browser could not reach Azure OpenAI (often blocked by CORS). Label matching was used instead.',
    UploadGroupName: 'Upload destination',
    LibraryNameLabel: 'Document library',
    LibraryNameDescription: 'Usually Project Documents.',
    FolderPathTemplateLabel: 'Folder path template',
    FolderPathTemplateDescription: 'Folder under Project Documents. Default is {Project Number}.',
    UploadButton: 'Upload',
    UploadHint: 'Upload always sends the original PDF you chose, not the OCR preview. Convert only fills fields. Name is taken from the PDF file name. Upload uses Leading BL to choose the business line site, then saves the PDF in that site\'s Project Documents folder named after Project Number. Name rules: 18 characters starting with I and a letter in position 14 go to InComing; 11 characters ending with a letter go to Outgoing. The site must have IsActive = Yes in Root URL Mapping List.',
    UploadDestinationLabel: 'Destination',
    UploadDestinationPending: 'Select Leading BL to choose the destination site',
    LeadingBlPlaceholder: 'Select a business line',
    ProjectNumberPlaceholder: 'Up to 8 digits',
    ProjectNumberDescription: 'Digits only, maximum 8.',
    RegistrationNumberPlaceholder: 'Copied from Name',
    RegistrationNumberDescription: 'Same as Name. This field is read only.',
    IssueDateLabel: 'Issue Date (dd/MM/yyyy)',
    IssueDatePlaceholder: 'dd/MM/yyyy',
    IssueDateDescription: 'Date format: dd/MM/yyyy',
    UploadInvalidProjectNumber: 'Project Number must be 1 to 8 digits.',
    UploadNeedFile: 'Choose a PDF before uploading.',
    UploadMissingFields: 'Fill these required fields before uploading: {0}',
    RequiredFieldError: 'This field is required.',
    RequiredFieldsPrompt: 'Please fill the required fields: {0}',
    UploadUnknownLeadingBl: 'Leading BL "{0}" does not match a business line site. Choose a listed business line.',
    UploadStarting: 'Preparing upload…',
    UploadCheckingMapping: 'Checking Root URL Mapping List…',
    UploadReadingSite: 'Reading destination site…',
    UploadFindingLibrary: 'Finding Project Documents…',
    UploadCreatingFolder: 'Creating folder…',
    UploadSendingFile: 'Uploading PDF…',
    UploadUpdatingFields: 'Updating library fields…',
    UploadSucceeded: 'Uploaded {0}.',
    UploadFailed: 'Upload failed.',
    OpenUploadedFile: 'Open file',
    AddFieldButton: 'Add field',
    DefaultFieldLabel: 'Field {0}',
    FieldPlaceholder: 'Highlight PDF text to fill this box',
    NamePlaceholder: 'Taken from the PDF file name',
    NameDescription: 'Filled from the PDF file name. Incoming and Outgoing folder rules still use this value.',
    HighlightHint: 'After Convert, fields are filled automatically. Click a field and highlight the PDF to correct a value.',
    FillSelectionButton: 'Fill selection',
    SelectFieldFirst: 'Select a field first, then highlight text.',
    NoTextSelected: 'Select text in the OCR result first.',
    ClearField: 'Clear field',
    CopyButton: 'Copy text',
    ClearButton: 'Clear',
    Copied: 'Text copied to the clipboard.',
    CopyFailed: 'Unable to copy text. Select the textarea and copy manually.',
    InvalidFileType: 'Please choose a PDF file.',
    OcrFailed: 'OCR failed. Please try another file or a smaller PDF.',
    LoadingEngine: 'Loading OCR engine and language data…',
    RenderingPage: 'Rendering page',
    OcrPage: 'Recognizing page',
    Of: 'of',
    Completed: 'Completed',
    PageProgress: 'Page {0} of {1}',
    Dismiss: 'Dismiss',
    LanguageEnglish: 'English',
    LanguageTraditionalChinese: 'Traditional Chinese',
    LanguageSimplifiedChinese: 'Simplified Chinese',
    LanguageEnglishTraditionalChinese: 'English + Traditional Chinese',
    LanguageEnglishSimplifiedChinese: 'English + Simplified Chinese'
    // loc bundle
  };
});
